# Site settings
title: Diana's Profile
email: Diana.K.Chen@asu.edu
description: > # this means to ignore newlines until "baseurl:"
  Diana K. Chen's Portfolio
baseurl: "/patchwork-gh-pages-24"
url: "http://dchen97.github.io"
twitter_username: ChenDkchen1
github_username:  dchen97
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
